import purityDashboardPRO from "assets/img/homepage/purity-dashboard-pro.png";
import purityDashboard from "assets/img/homepage/purity-dashboard.png";
import uranusWireframe from "assets/img/homepage/uranus-wireframe-kit.png";
import uranusWireframePRO from "assets/img/homepage/uranus-wireframe-pro.png";
import venusFree from "assets/img/homepage/venus-db-free.png";
import venusPro from "assets/img/homepage/venus-db-pro.png";
import venusSystem from "assets/img/homepage/venus-design-system.png";
import glassy from "assets/img/templates/glassy.png";
import saturnUI from "assets/img/templates/saturn-ui.png";
import taskUI from "assets/img/templates/task-ui.png";
import venusSystemFree from "assets/img/templates/venus-system-free.png";
import visionReactPRO from "assets/img/homepage/vision-react-pro.png";
import visionReactFree from "assets/img/homepage/vision-react-free.png";

export const templatesProducts = {
  alltemplates: [
    {
      image: visionReactPRO,
      date: "Jan 04 2022 12:00:00 AM",
      tag: "Dashboard",
      price: 69,
      keywords: [
        "vision",
        "frontend",
        "design",
        "react",
        "figma",
        "tool",
        "dashboard",
        "dark mode",
        "premium",
      ],
      title: "Vision UI PRO React",
      downloads: 14,
      category: "React Products",
      path: "/product/vision-ui-dashboard-pro-react",
    },
    {
      image: visionReactFree,
      date: "Jan 04 2022 11:00:00 AM",
      tag: "Dashboard",
      price: 0,
      keywords: [
        "vision",
        "frontend",
        "design",
        "react",
        "figma",
        "tool",
        "dashboard",
        "dark mode",
        "free",
      ],
      title: "Vision UI Dashboard React",
      downloads: 10,
      category: "React Products",
      path: "/product/vision-ui-dashboard-react",
    },
    {
      image: venusSystem,
      date: "Jun 01 2021 10:00:00 AM",
      tag: "Design Tool",
      price: 99,
      keywords: [
        "venus",
        "frontend",
        "design",
        "system",
        "figma",
        "tool",
        "vdb",
        "dark mode",
        "free",
      ],
      title: "Venus Design System PRO",
      downloads: 12,
      category: "Figma Products",
      path: "/product/venus-design-system-pro",
    },
    {
      image: venusPro,
      date: "Aug 30 2021 10:00:00 AM",
      tag: "Design Tool",
      price: 59,
      keywords: [
        "venus",
        "frontend",
        "design",
        "figma",
        "tool",
        "vdb",
        "dashboard",
        "builder",
        "dark mode",
        "premium",
      ],
      title: "Venus DB PRO",
      downloads: 27,
      category: "Freebies, Figma Products",
      path: "/product/venus-db-pro",
    },
    {
      image: uranusWireframePRO,
      date: "Mar 12 2018 10:00:00 AM",
      tag: "Web Tool",
      price: 69,
      keywords: [
        "uranus",
        "web",
        "frontend",
        "tool",
        "wireframe",
        "kit",
        "css",
        "html",
        "bootstrap",
        "bootstrap5",
        "dark mode",
        "premium",
      ],
      title: "Uranus Wireframe Kit PRO",
      downloads: 0,
      category: "UI Kits, Figma Products",
      path: "/product/uranus-wireframe-pro",
    },
    {
      image: purityDashboardPRO,
      date: "Oct 30 2021 10:00:00 AM",
      tag: "Dashboard",
      price: 69,
      keywords: [
        "purity",
        "purity ui",
        "web",
        "frontend",
        "dashboard",
        "chakra",
        "react",
        "reactjs",
        "dark mode",
        "premium",
      ],
      title: "Purity UI Dashboard PRO",
      downloads: 3,
      category: "Coded, Figma, Dashboards",
      path: "/product/purity-dashboard-pro",
    },
    {
      image: purityDashboard,
      date: "Oct 12 2021 10:00:00 AM",
      tag: "Dashboard",
      price: 0,
      keywords: [
        "purity ui",
        "web",
        "frontend",
        "dashboard",
        "chakra",
        "react",
        "reactjs",
        "dark mode",
        "free",
      ],
      title: "Purity UI Dashboard Free",
      downloads: 1723,
      category: "Coded, Figma, Dashboards",
      path: "/product/purity-dashboard-free",
    },
    {
      image: venusFree,
      date: "Aug 12 2021 10:00:00 AM",
      tag: "Design Tool",
      price: 0,
      keywords: [
        "venus",
        "frontend",
        "design",
        "figma",
        "tool",
        "vdb",
        "dashboard",
        "builder",
        "dark mode",
        "free",
      ],
      title: "Venus DB Free",
      downloads: 172,
      category: "Freebies, Figma Products",
      path: "/product/venus-db-free",
    },
    {
      image: venusSystemFree,
      date: "Mar 12 2020 10:00:00 AM",
      title: "Venus Design System Free",
      downloads: 1241,
      tag: "Design Tool",
      price: 0,
      keywords: [
        "venus",
        "frontend",
        "design",
        "system",
        "figma",
        "tool",
        "vdb",
        "dark mode",
        "free",
      ],
      category: "Freebies, Figma Products",
      path: "/product/venus-design-system-free",
    },
    {
      image: uranusWireframe,
      date: "Mar 12 2013 10:00:00 AM",
      title: "Uranus Wireframe Kit Free",
      downloads: 640,
      tag: "Design Tool",
      price: 0,
      keywords: [
        "web",
        "frontend",
        "tool",
        "wireframe",
        "kit",
        "css",
        "html",
        "bootstrap",
        "bootstrap5",
        "dark mode",
        "free",
      ],
      category: "UI Kits, Freebies, Figma Products",
      path: "/product/uranus-wireframe-free",
    },
    {
      image: glassy,
      date: "Mar 12 2010 10:00:00 AM",
      tag: "Design Tool",
      title: "Glassy - Glassmorphism Cards",
      downloads: 181,
      category: "UI Kits, Freebies, Figma Products",
      price: 0,
      keywords: [
        "glassy",
        "web",
        "frontend",
        "tool",
        "figma",
        "freebies",
        "kit",
        "free",
      ],
      path: "/product/glassy-cards",
    },
    {
      image: taskUI,
      date: "Mar 12 2009 10:00:00 AM",
      tag: "Web Tool",
      title: "Task List UI - React App",
      downloads: 88,
      category: "Category: Freebies, Coded, Adobe XD",
      price: 0,
      keywords: [
        "task",
        "adobe",
        "xd",
        "frontend",
        "tool",
        "react",
        "reactjs",
        "freebies",
        "free",
      ],
      path: "/product/task-list-ui",
    },
    {
      image: saturnUI,
      date: "Mar 12 2008 10:00:00 AM",
      title: "Saturn - UI Kit Headers",
      downloads: 107,
      tag: "UI Kit",
      category: "Category: Freebies, Figma Products",
      price: 0,
      keywords: [
        "saturn",
        "headers",
        "ui",
        "frontend",
        "figma",
        "wireframe",
        "kit",
        "dark mode",
        "freebies",
        "free",
      ],
      path: "/product/saturn-ui-kit",
    },
  ],
  admindashboards: [
    {
      image: visionReactPRO,
      date: "Jan 04 2022 12:00:00 AM",
      tag: "Dashboard",
      price: 69,
      keywords: [
        "vision",
        "frontend",
        "design",
        "react",
        "figma",
        "tool",
        "dashboard",
        "dark mode",
        "premium",
      ],
      title: "Vision UI PRO React",
      downloads: 14,
      category: "React Products",
      path: "/product/vision-ui-dashboard-pro-react",
    },
    {
      image: visionReactFree,
      date: "Jan 04 2022 11:00:00 AM",
      tag: "Dashboard",
      price: 0,
      keywords: [
        "vision",
        "frontend",
        "design",
        "react",
        "figma",
        "tool",
        "dashboard",
        "dark mode",
        "free",
      ],
      title: "Vision UI Dashboard React",
      downloads: 10,
      category: "React Products",
      path: "/product/vision-ui-dashboard-react",
    },
    {
      image: venusFree,
      date: "Sep 12 2021 10:00:00 AM",
      tag: "Design Tool",
      price: 0,
      title: "Venus DB Free",
      downloads: 172,
      category: "Freebies, Figma Products",
      path: "/product/venus-db-free",
    },
    {
      image: purityDashboardPRO,
      date: "Oct 12 2021 10:00:00 AM",
      tag: "Dashboard",
      price: 69,
      title: "Purity UI Dashboard PRO",
      downloads: 3,
      category: "Coded, Figma, Dashboards",
      path: "/product/purity-dashboard-pro",
    },
    {
      image: venusFree,
      date: "Sep 12 2021 10:00:00 AM",
      tag: "Design Tool",
      price: 0,
      title: "Venus DB Free",
      downloads: 172,
      category: "Freebies, Figma Products",
      path: "/product/venus-db-free",
    },
    {
      image: purityDashboard,
      date: "Oct 12 2021 10:00:00 AM",
      tag: "Dashboard",
      price: 0,
      title: "Purity UI Dashboard Free",
      downloads: 1723,
      category: "Coded, Figma, Dashboards",
      path: "/product/purity-dashboard-free",
    },
  ],
  uikits: [
    {
      image: venusSystem,
      date: "Jun 01 2021 10:00:00 AM",
      tag: "Design Tool",
      price: 99,
      title: "Venus Design System PRO",
      downloads: 12,
      category: "Figma Products",
      path: "/product/venus-design-system-pro",
    },
    {
      image: venusFree,
      date: "Sep 12 2021 10:00:00 AM",
      tag: "Design Tool",
      price: 0,
      title: "Venus DB Free",
      downloads: 172,
      category: "Freebies, Figma Products",
      path: "/product/venus-db-free",
    },
    {
      image: uranusWireframePRO,
      date: "Mar 12 2018 10:00:00 AM",
      tag: "Web Tool",
      price: 69,
      title: "Uranus Wireframe Kit PRO",
      downloads: 0,
      category: "UI Kits, Figma Products",
      path: "/product/uranus-wireframe-pro",
    },
    {
      image: venusFree,
      date: "Sep 12 2021 10:00:00 AM",
      tag: "Design Tool",
      price: 0,
      title: "Venus DB Free",
      downloads: 172,
      category: "Freebies, Figma Products",
      path: "/product/venus-db-free",
    },
    {
      image: venusSystemFree,
      date: "Mar 12 2020 10:00:00 AM",
      title: "Venus Design System Free",
      downloads: 1241,
      tag: "Design Tool",
      price: 0,
      category: "Freebies, Figma Products",
      path: "/product/venus-design-system-free",
    },
    {
      image: uranusWireframe,
      date: "Mar 12 2013 10:00:00 AM",
      title: "Uranus Wireframe Kit Free",
      downloads: 640,
      tag: "Design Tool",
      price: 0,
      category: "UI Kits, Freebies, Figma Products",
      path: "/product/uranus-wireframe-free",
    },
    {
      image: glassy,
      date: "Mar 12 2010 10:00:00 AM",
      tag: "Design Tool",
      title: "Glassy - Glassmorphism Cards",
      downloads: 181,
      category: "UI Kits, Freebies, Figma Products",
      price: 0,
      path: "/product/glassy-cards",
    },
    {
      image: taskUI,
      date: "Mar 12 2009 10:00:00 AM",
      tag: "Web Tool",
      title: "Task List UI - React App",
      downloads: 88,
      category: "Category: Freebies, Coded, Adobe XD",
      price: 0,
      path: "/product/task-list-ui",
    },
    {
      image: saturnUI,
      date: "Mar 12 2008 10:00:00 AM",
      title: "Saturn - UI Kit Headers",
      downloads: 107,
      tag: "UI Kit",
      category: "Category: Freebies, Figma Products",
      price: 0,
      path: "/product/saturn-ui-kit",
    },
  ],
  freetemplates: [
    {
      image: visionReactFree,
      date: "Jan 04 2022 11:00:00 AM",
      tag: "Dashboard",
      price: 0,
      keywords: [
        "vision",
        "frontend",
        "design",
        "react",
        "figma",
        "tool",
        "dashboard",
        "dark mode",
        "free",
      ],
      title: "Vision UI Dashboard React",
      downloads: 10,
      category: "React Products",
      path: "/product/vision-ui-dashboard-react",
    },
    {
      image: venusFree,
      date: "Sep 12 2021 10:00:00 AM",
      tag: "Design Tool",
      price: 0,
      title: "Venus DB Free",
      downloads: 172,
      category: "Freebies, Figma Products",
      path: "/product/venus-db-free",
    },
    {
      image: venusSystemFree,
      date: "Mar 12 2020 10:00:00 AM",
      title: "Venus Design System Free",
      downloads: 1241,
      tag: "Design Tool",
      price: 0,
      category: "Freebies, Figma Products",
      path: "/product/venus-design-system-free",
    },
    {
      image: uranusWireframe,
      date: "Mar 12 2013 10:00:00 AM",
      title: "Uranus Wireframe Kit Free",
      downloads: 640,
      tag: "Design Tool",
      price: 0,
      category: "UI Kits, Freebies, Figma Products",
      path: "/product/uranus-wireframe-free",
    },
    {
      image: glassy,
      date: "Mar 12 2010 10:00:00 AM",
      tag: "Design Tool",
      title: "Glassy - Glassmorphism Cards",
      downloads: 181,
      category: "UI Kits, Freebies, Figma Products",
      price: 0,
      path: "/product/glassy-cards",
    },
    {
      image: taskUI,
      date: "Mar 12 2009 10:00:00 AM",
      tag: "Web Tool",
      title: "Task List UI - React App",
      downloads: 88,
      category: "Category: Freebies, Coded, Adobe XD",
      price: 0,
      path: "/product/task-list-ui",
    },
    {
      image: saturnUI,
      date: "Mar 12 2008 10:00:00 AM",
      title: "Saturn - UI Kit Headers",
      downloads: 107,
      tag: "UI Kit",
      category: "Category: Freebies, Figma Products",
      price: 0,
      path: "/product/saturn-ui-kit",
    },
    {
      image: purityDashboard,
      date: "Oct 12 2021 10:00:00 AM",
      tag: "Dashboard",
      price: 0,
      title: "Purity UI Dashboard Free",
      downloads: 1723,
      category: "Coded, Figma, Dashboards",
      path: "/purity-dashboard-free",
    },
  ],
  premiumtemplates: [
    {
      image: visionReactPRO,
      date: "Jan 04 2022 12:00:00 AM",
      tag: "Dashboard",
      price: 69,
      keywords: [
        "vision",
        "frontend",
        "design",
        "react",
        "figma",
        "tool",
        "dashboard",
        "dark mode",
        "premium",
      ],
      title: "Vision UI PRO React",
      downloads: 14,
      category: "React Products",
      path: "/product/vision-ui-dashboard-pro-react",
    },
    {
      image: venusSystem,
      date: "Jun 01 2021 10:00:00 AM",
      tag: "Design Tool",
      price: 99,
      title: "Venus Design System PRO",
      downloads: 12,
      category: "Figma Products",
      path: "/product/venus-design-system-pro",
    },
    {
      image: uranusWireframePRO,
      date: "Mar 12 2018 10:00:00 AM",
      tag: "Web Tool",
      price: 69,
      title: "Uranus Wireframe Kit PRO",
      downloads: 0,
      category: "UI Kits, Figma Products",
      path: "/product/uranus-wireframe-pro",
    },
    {
      image: purityDashboardPRO,
      date: "Oct 12 2021 10:00:00 AM",
      tag: "Dashboard",
      price: 69,
      title: "Purity UI Dashboard PRO",
      downloads: 3,
      category: "Coded, Figma, Dashboards",
      path: "/product/purity-dashboard-pro",
    },
    {
      image: venusPro,
      date: "Mar 12 2019 10:00:00 AM",
      tag: "Design Tool",
      price: 59,
      title: "Venus DB PRO",
      downloads: 27,
      category: "Freebies, Figma Products",
      path: "/product/venus-db-pro",
    },
  ],
  figma: [
    {
      image: visionReactPRO,
      date: "Jan 04 2022 12:00:00 AM",
      tag: "Dashboard",
      price: 69,
      keywords: [
        "vision",
        "frontend",
        "design",
        "react",
        "figma",
        "tool",
        "dashboard",
        "dark mode",
        "premium",
      ],
      title: "Vision UI PRO React",
      downloads: 14,
      category: "React Products",
      path: "/product/vision-ui-dashboard-pro-react",
    },
    {
      image: visionReactFree,
      date: "Jan 04 2022 11:00:00 AM",
      tag: "Dashboard",
      price: 0,
      keywords: [
        "vision",
        "frontend",
        "design",
        "react",
        "figma",
        "tool",
        "dashboard",
        "dark mode",
        "free",
      ],
      title: "Vision UI Dashboard React",
      downloads: 10,
      category: "React Products",
      path: "/product/vision-ui-dashboard-react",
    },
    {
      image: venusSystem,
      date: "Jun 01 2021 10:00:00 AM",
      tag: "Design Tool",
      price: 99,
      title: "Venus Design System PRO",
      downloads: 12,
      category: "Figma Products",
      path: "/product/venus-design-system-pro",
    },
    {
      image: venusPro,
      date: "Aug 30 2021 10:00:00 AM",
      tag: "Design Tool",
      price: 59,
      title: "Venus DB PRO",
      downloads: 27,
      category: "Freebies, Figma Products",
      path: "/product/venus-db-pro",
    },
    {
      image: uranusWireframePRO,
      date: "Mar 12 2018 10:00:00 AM",
      tag: "Web Tool",
      price: 69,
      title: "Uranus Wireframe Kit PRO",
      downloads: 0,
      category: "UI Kits, Figma Products",
      path: "/product/uranus-wireframe-pro",
    },
    {
      image: purityDashboardPRO,
      date: "Oct 12 2021 10:00:00 AM",
      tag: "Dashboard",
      price: 69,
      title: "Purity UI Dashboard PRO",
      downloads: 3,
      category: "Coded, Figma, Dashboards",
      path: "/product/purity-dashboard-pro",
    },
    {
      image: venusFree,
      date: "Sep 12 2021 10:00:00 AM",
      tag: "Design Tool",
      price: 0,
      title: "Venus DB Free",
      downloads: 172,
      category: "Freebies, Figma Products",
      path: "/product/venus-db-free",
    },
    {
      image: venusSystemFree,
      date: "Mar 12 2020 10:00:00 AM",
      title: "Venus Design System Free",
      downloads: 1241,
      tag: "Design Tool",
      price: 0,
      category: "Freebies, Figma Products",
      path: "/product/venus-design-system-free",
    },
    {
      image: uranusWireframe,
      date: "Mar 12 2013 10:00:00 AM",
      title: "Uranus Wireframe Kit Free",
      downloads: 640,
      tag: "Design Tool",
      price: 0,
      category: "UI Kits, Freebies, Figma Products",
      path: "/product/uranus-wireframe-free",
    },
    {
      image: glassy,
      date: "Mar 12 2010 10:00:00 AM",
      tag: "Design Tool",
      title: "Glassy - Glassmorphism Cards",
      downloads: 181,
      category: "UI Kits, Freebies, Figma Products",
      price: 0,
      path: "/product/glassy-cards",
    },
    {
      image: purityDashboard,
      date: "Oct 12 2021 10:00:00 AM",
      tag: "Dashboard",
      price: 0,
      title: "Purity UI Dashboard Free",
      downloads: 1723,
      category: "Coded, Figma, Dashboards",
      path: "/product/purity-dashboard-free",
    },
  ],
  react: [
    {
      image: visionReactPRO,
      date: "Jan 04 2022 12:00:00 AM",
      tag: "Dashboard",
      price: 69,
      keywords: [
        "vision",
        "frontend",
        "design",
        "react",
        "figma",
        "tool",
        "dashboard",
        "dark mode",
        "premium",
      ],
      title: "Vision UI PRO React",
      downloads: 14,
      category: "React Products",
      path: "/product/vision-ui-dashboard-pro-react",
    },
    {
      image: visionReactFree,
      date: "Jan 04 2022 11:00:00 AM",
      tag: "Dashboard",
      price: 0,
      keywords: [
        "vision",
        "frontend",
        "design",
        "react",
        "figma",
        "tool",
        "dashboard",
        "dark mode",
        "free",
      ],
      title: "Vision UI Dashboard React",
      downloads: 10,
      category: "React Products",
      path: "/product/vision-ui-dashboard-react",
    },
    {
      image: purityDashboardPRO,
      date: "Oct 12 2021 10:00:00 AM",
      tag: "Dashboard",
      price: 69,
      title: "Purity UI Dashboard PRO",
      downloads: 3,
      category: "Coded, Figma, Dashboards",
      path: "/product/purity-dashboard-pro",
    },
    {
      image: taskUI,
      date: "Mar 12 2009 10:00:00 AM",
      tag: "Web Tool",
      title: "Task List UI - React App",
      downloads: 88,
      category: "Category: Freebies, Coded, Adobe XD",
      price: 0,
      path: "/product/task-list-ui",
    },
    {
      image: purityDashboard,
      date: "Oct 12 2021 10:00:00 AM",
      tag: "Dashboard",
      price: 0,
      title: "Purity UI Dashboard Free",
      downloads: 1723,
      category: "Coded, Figma, Dashboards",
      path: "/purity-dashboard-free",
    },
  ],
  bootstrap: [
    {
      image: uranusWireframePRO,
      description: [""],
      date: "Mar 12 2018 10:00:00 AM",
      tag: "Web Tool",
      price: 69,
      title: "Uranus Wireframe Kit PRO",
      downloads: 0,
      category: "UI Kits, Figma Products",
      path: "/product/uranus-wireframe-pro",
    },
    {
      image: uranusWireframe,
      date: "Mar 12 2013 10:00:00 AM",
      title: "Uranus Wireframe Kit Free",
      downloads: 640,
      tag: "Design Tool",
      price: 0,
      category: "UI Kits, Freebies, Figma Products",
      path: "/product/uranus-wireframe-free",
    },
  ],
};
