import venusPro from "assets/img/homepage/venus-db-pro.png";
import venusSystem from "assets/img/homepage/venus-design-system.png";
import uranusWireframe from "assets/img/homepage/uranus-wireframe-kit.png";
import purityDashboard from "assets/img/homepage/purity-dashboard.png";
import venusFree from "assets/img/homepage/venus-db-free.png";
import puritySensual from "assets/img/homepage/purity-sensual-kit.png";
import venusSystemFree from "assets/img/templates/venus-system-free.png";
import uranusWireframeFree from "assets/img/templates/uranus-free.png";
import glassy from "assets/img/templates/glassy.png";
import taskUI from "assets/img/templates/task-ui.png";
import saturnUI from "assets/img/templates/saturn-ui.png";

export const templatesProducts = {
  alltemplates: [
    {
      image: venusSystem,
      date: "Mar 12 2017 10:00:00 AM",
      tag: "Design Tool",
      price: 99,
      title: "Venus Design System",
      downloads: 12,
      category: "Figma Products",
      path: "/",
    },
    {
      image: venusPro,
      date: "Mar 12 2019 10:00:00 AM",
      tag: "Design Tool",
      price: 59,
      title: "Venus DB PRO",
      downloads: 27,
      category: "Freebies, Figma Products",
      path: "/",
    },
    {
      image: uranusWireframe,
      date: "Mar 12 2018 10:00:00 AM",
      tag: "Web Tool",
      price: 48,
      title: "Uranus Wireframe Kit",
      downloads: 0,
      category: "UI Kits, Figma Products",
      path: "/",
    },
    {
      image: purityDashboard,
      date: "Mar 12 2018 10:00:00 AM",
      tag: "Dashboard",
      price: 79,
      title: "Purity UI Dashboard PRO",
      downloads: 3,
      category: "Coded, Figma, Dashboards",
      path: "/",
    },
    {
      image: purityDashboard,
      date: "Mar 12 2018 10:00:00 AM",
      tag: "Dashboard",
      price: 0,
      title: "Purity UI Dashboard Free",
      downloads: 1723,
      category: "Coded, Figma, Dashboards",
      path: "/",
    },
    {
      image: venusFree,
      date: "Mar 12 2019 10:00:00 AM",
      tag: "Design Tool",
      price: 0,
      title: "Venus DB Free",
      downloads: 172,
      category: "Freebies, Figma Products",
      path: "/",
    },
    {
      image: venusSystemFree,
      date: "Mar 12 2020 10:00:00 AM",
      title: "Venus Design System Free",
      downloads: 1241,
      tag: "Design Tool",
      price: 0,
      category: "Freebies, Figma Products",
      path: "/",
    },
    {
      image: uranusWireframeFree,
      date: "Mar 12 2013 10:00:00 AM",
      title: "Uranus Wireframe Kit Free",
      downloads: 640,
      tag: "Design Tool",
      price: 0,
      category: "UI Kits, Freebies, Figma Products",
      path: "/",
    },
    {
      image: glassy,
      date: "Mar 12 2010 10:00:00 AM",
      tag: "Design Tool",
      title: "Glassy - Glassmorphism Cards",
      downloads: 181,
      category: "UI Kits, Freebies, Figma Products",
      price: 0,
      path: "/",
    },
    {
      image: taskUI,
      date: "Mar 12 2009 10:00:00 AM",
      tag: "Web Tool",
      title: "Task List UI - React App",
      downloads: 88,
      category: "Category: Freebies, Coded, Adobe XD",
      price: 0,
      path: "/",
    },
    {
      image: saturnUI,
      date: "Mar 12 2008 10:00:00 AM",
      title: "Saturn - UI Kit Headers",
      downloads: 107,
      tag: "UI Kit",
      category: "Category: Freebies, Figma Products",
      price: 0,
      path: "/",
    }
  ],
  admindashboards: [
    {
      image: venusFree,
      date: "Mar 12 2019 10:00:00 AM",
      tag: "Design Tool",
      price: 0,
      title: "Venus DB Free",
      downloads: 172,
      category: "Freebies, Figma Products",
      path: "/",
    },
    {
      image: uranusWireframe,
      date: "Mar 12 2018 10:00:00 AM",
      tag: "Web Tool",
      price: 48,
      title: "Uranus Wireframe Kit",
      downloads: 0,
      category: "UI Kits, Figma Products",
      path: "/",
    },
    {
      image: purityDashboard,
      date: "Mar 12 2018 10:00:00 AM",
      tag: "Dashboard",
      price: 79,
      title: "Purity UI Dashboard PRO",
      downloads: 3,
      category: "Coded, Figma, Dashboards",
      path: "/",
    },
    {
      image: venusFree,
      date: "Mar 12 2019 10:00:00 AM",
      tag: "Design Tool",
      price: 0,
      title: "Venus DB Free",
      downloads: 172,
      category: "Freebies, Figma Products",
      path: "/",
    },
    {
      image: purityDashboard,
      date: "Mar 12 2018 10:00:00 AM",
      tag: "Dashboard",
      price: 0,
      title: "Purity UI Dashboard Free",
      downloads: 1723,
      category: "Coded, Figma, Dashboards",
      path: "/",
    },
    
  ],
  uikits: [
    {
      image: venusSystem,
      date: "Mar 12 2017 10:00:00 AM",
      tag: "Design Tool",
      price: 99,
      title: "Venus Design System",
      downloads: 12,
      category: "Figma Products",
      path: "/",
    },
    {
      image: venusFree,
      date: "Mar 12 2019 10:00:00 AM",
      tag: "Design Tool",
      price: 0,
      title: "Venus DB Free",
      downloads: 172,
      category: "Freebies, Figma Products",
      path: "/",
    },
    {
      image: uranusWireframe,
      date: "Mar 12 2018 10:00:00 AM",
      tag: "Web Tool",
      price: 48,
      title: "Uranus Wireframe Kit",
      downloads: 0,
      category: "UI Kits, Figma Products",
      path: "/",
    },
    {
      image: venusFree,
      date: "Mar 12 2019 10:00:00 AM",
      tag: "Design Tool",
      price: 0,
      title: "Venus DB Free",
      downloads: 172,
      category: "Freebies, Figma Products",
      path: "/",
    },
    {
      image: venusSystemFree,
      date: "Mar 12 2020 10:00:00 AM",
      title: "Venus Design System Free",
      downloads: 1241,
      tag: "Design Tool",
      price: 0,
      category: "Freebies, Figma Products",
      path: "/",
    },
    {
      image: uranusWireframeFree,
      date: "Mar 12 2013 10:00:00 AM",
      title: "Uranus Wireframe Kit Free",
      downloads: 640,
      tag: "Design Tool",
      price: 0,
      category: "UI Kits, Freebies, Figma Products",
      path: "/",
    },
    {
      image: glassy,
      date: "Mar 12 2010 10:00:00 AM",
      tag: "Design Tool",
      title: "Glassy - Glassmorphism Cards",
      downloads: 181,
      category: "UI Kits, Freebies, Figma Products",
      price: 0,
      path: "/",
    },
    {
      image: taskUI,
      date: "Mar 12 2009 10:00:00 AM",
      tag: "Web Tool",
      title: "Task List UI - React App",
      downloads: 88,
      category: "Category: Freebies, Coded, Adobe XD",
      price: 0,
      path: "/",
    },
    {
      image: saturnUI,
      date: "Mar 12 2008 10:00:00 AM",
      title: "Saturn - UI Kit Headers",
      downloads: 107,
      tag: "UI Kit",
      category: "Category: Freebies, Figma Products",
      price: 0,
      path: "/",
    }
    
  ],
  freetemplates: [
    {
      image: venusFree,
      date: "Mar 12 2019 10:00:00 AM",
      tag: "Design Tool",
      price: 0,
      title: "Venus DB Free",
      downloads: 172,
      category: "Freebies, Figma Products",
      path: "/",
    },
    {
      image: venusSystemFree,
      date: "Mar 12 2020 10:00:00 AM",
      title: "Venus Design System Free",
      downloads: 1241,
      tag: "Design Tool",
      price: 0,
      category: "Freebies, Figma Products",
      path: "/",
    },
    {
      image: uranusWireframeFree,
      date: "Mar 12 2013 10:00:00 AM",
      title: "Uranus Wireframe Kit Free",
      downloads: 640,
      tag: "Design Tool",
      price: 0,
      category: "UI Kits, Freebies, Figma Products",
      path: "/",
    },
    {
      image: glassy,
      date: "Mar 12 2010 10:00:00 AM",
      tag: "Design Tool",
      title: "Glassy - Glassmorphism Cards",
      downloads: 181,
      category: "UI Kits, Freebies, Figma Products",
      price: 0,
      path: "/",
    },
    {
      image: taskUI,
      date: "Mar 12 2009 10:00:00 AM",
      tag: "Web Tool",
      title: "Task List UI - React App",
      downloads: 88,
      category: "Category: Freebies, Coded, Adobe XD",
      price: 0,
      path: "/",
    },
    {
      image: saturnUI,
      date: "Mar 12 2008 10:00:00 AM",
      title: "Saturn - UI Kit Headers",
      downloads: 107,
      tag: "UI Kit",
      category: "Category: Freebies, Figma Products",
      price: 0,
      path: "/",
    },
    {
      image: purityDashboard,
      date: "Mar 12 2018 10:00:00 AM",
      tag: "Dashboard",
      price: 0,
      title: "Purity UI Dashboard Free",
      downloads: 1723,
      category: "Coded, Figma, Dashboards",
      path: "/",
    },
  ],
  premiumtemplates: [
    {
      image: venusSystem,
      date: "Mar 12 2017 10:00:00 AM",
      tag: "Design Tool",
      price: 99,
      title: "Venus Design System",
      downloads: 12,
      category: "Figma Products",
      path: "/",
    },
    {
      image: uranusWireframe,
      date: "Mar 12 2018 10:00:00 AM",
      tag: "Web Tool",
      price: 48,
      title: "Uranus Wireframe Kit",
      downloads: 0,
      category: "UI Kits, Figma Products",
      path: "/",
    },
    {
      image: purityDashboard,
      date: "Mar 12 2018 10:00:00 AM",
      tag: "Dashboard",
      price: 79,
      title: "Purity UI Dashboard PRO",
      downloads: 3,
      category: "Coded, Figma, Dashboards",
      path: "/",
    },
    {
      image: venusPro,
      date: "Mar 12 2019 10:00:00 AM",
      tag: "Design Tool",
      price: 59,
      title: "Venus DB PRO",
      downloads: 27,
      category: "Freebies, Figma Products",
      path: "/",
    },
  ],
  figma: [
    {
      image: venusSystem,
      date: "Mar 12 2017 10:00:00 AM",
      tag: "Design Tool",
      price: 99,
      title: "Venus Design System",
      downloads: 12,
      category: "Figma Products",
      path: "/",
    },
    {
      image: venusFree,
      date: "Mar 12 2019 10:00:00 AM",
      tag: "Design Tool",
      price: 0,
      title: "Venus DB Free",
      downloads: 172,
      category: "Freebies, Figma Products",
      path: "/",
    },
    {
      image: uranusWireframe,
      date: "Mar 12 2018 10:00:00 AM",
      tag: "Web Tool",
      price: 48,
      title: "Uranus Wireframe Kit",
      downloads: 0,
      category: "UI Kits, Figma Products",
      path: "/",
    },
    {
      image: purityDashboard,
      date: "Mar 12 2018 10:00:00 AM",
      tag: "Dashboard",
      price: 79,
      title: "Purity UI Dashboard PRO",
      downloads: 3,
      category: "Coded, Figma, Dashboards",
      path: "/",
    },
    {
      image: venusFree,
      date: "Mar 12 2019 10:00:00 AM",
      tag: "Design Tool",
      price: 0,
      title: "Venus DB Free",
      downloads: 172,
      category: "Freebies, Figma Products",
      path: "/",
    },
    {
      image: venusSystemFree,
      date: "Mar 12 2020 10:00:00 AM",
      title: "Venus Design System Free",
      downloads: 1241,
      tag: "Design Tool",
      price: 0,
      category: "Freebies, Figma Products",
      path: "/",
    },
    {
      image: uranusWireframeFree,
      date: "Mar 12 2013 10:00:00 AM",
      title: "Uranus Wireframe Kit Free",
      downloads: 640,
      tag: "Design Tool",
      price: 0,
      category: "UI Kits, Freebies, Figma Products",
      path: "/",
    },
    {
      image: glassy,
      date: "Mar 12 2010 10:00:00 AM",
      tag: "Design Tool",
      title: "Glassy - Glassmorphism Cards",
      downloads: 181,
      category: "UI Kits, Freebies, Figma Products",
      price: 0,
      path: "/",
    },
    {
      image: purityDashboard,
      date: "Mar 12 2018 10:00:00 AM",
      tag: "Dashboard",
      price: 0,
      title: "Purity UI Dashboard Free",
      downloads: 1723,
      category: "Coded, Figma, Dashboards",
      path: "/",
    },
  ],
  react: [
    {
      image: purityDashboard,
      date: "Mar 12 2018 10:00:00 AM",
      tag: "Dashboard",
      price: 79,
      title: "Purity UI Dashboard PRO",
      downloads: 3,
      category: "Coded, Figma, Dashboards",
      path: "/",
    },
    {
      image: taskUI,
      date: "Mar 12 2009 10:00:00 AM",
      tag: "Web Tool",
      title: "Task List UI - React App",
      downloads: 88,
      category: "Category: Freebies, Coded, Adobe XD",
      price: 0,
      path: "/",
    },
    {
      image: purityDashboard,
      date: "Mar 12 2018 10:00:00 AM",
      tag: "Dashboard",
      price: 0,
      title: "Purity UI Dashboard Free",
      downloads: 1723,
      category: "Coded, Figma, Dashboards",
      path: "/",
    },
  ],
  bootstrap: [
    {
      image: uranusWireframe,
      date: "Mar 12 2018 10:00:00 AM",
      tag: "Web Tool",
      price: 48,
      title: "Uranus Wireframe Kit",
      downloads: 0,
      category: "UI Kits, Figma Products",
      path: "/",
    },
    {
      image: uranusWireframeFree,
      date: "Mar 12 2013 10:00:00 AM",
      title: "Uranus Wireframe Kit Free",
      downloads: 640,
      tag: "Design Tool",
      price: 0,
      category: "UI Kits, Freebies, Figma Products",
      path: "/",
    }
  ]
}